upstream laravel_cluster {
    # Phase 5: Passive Health Checks
    # Jika server gagal 3x dalam 10 detik, Nginx akan menganggapnya "mati" sementara
    server strukify-web-1:8000 max_fails=3 fail_timeout=10s;
    server strukify-web-2:8000 max_fails=3 fail_timeout=10s;
}

upstream ai_cluster {
    server strukify-ai-1:8001 max_fails=3 fail_timeout=15s;
    server strukify-ai-2:8001 max_fails=3 fail_timeout=15s;
}

server {
    listen 80;
    server_name localhost;

    # Load Balance API AI Scanner
    location /api/scan {
        proxy_pass http://ai_cluster;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_connect_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Load Balance Laravel Web App
    location / {
        proxy_pass http://laravel_cluster;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
